export const REQUEST_UPDATE_ACTIONS = {
  UPDATE_LAST_VIEWED_AT: "UPDATE_LAST_VIEWED_AT",
  APPROVE_REQUEST: "APPROVE_REQUEST",
  REJECT_REQUEST: "REJECT_REQUEST",
} as const;

export type RequestAction = (typeof REQUEST_UPDATE_ACTIONS)[keyof typeof REQUEST_UPDATE_ACTIONS];
